# Generated by Django 3.0 on 2019-12-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='路面类型',
            fields=[
                ('路面类型', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='路面类型')),
            ],
        ),
        migrations.CreateModel(
            name='车行道',
            fields=[
                ('车行道编号', models.AutoField(primary_key=True, serialize=False, verbose_name='车行道编号')),
                ('基层类型', models.CharField(max_length=12, verbose_name='基层类型')),
                ('基层厚度', models.FloatField(verbose_name='基层厚度')),
                ('车道数', models.IntegerField(verbose_name='车道数')),
                ('通行方向', models.CharField(max_length=20, verbose_name='通行方向')),
                ('机动车道宽度范围', models.CharField(max_length=100, verbose_name='机动车道宽度范围')),
                ('左侧非机动车道宽度范围', models.CharField(max_length=100, verbose_name='左侧非机动车道宽度范围')),
                ('右侧非机动车道宽度范围', models.CharField(max_length=100, verbose_name='右侧非机动车道宽度范围')),
                ('车行道面积', models.FloatField(verbose_name='车行道面积')),
                ('有无公交车专用道', models.CharField(max_length=4, verbose_name='有无公交车专用道')),
                ('侧石类型', models.CharField(max_length=12, verbose_name='侧石类型')),
                ('侧石长度', models.FloatField(verbose_name='侧石长度')),
                ('平石类型', models.CharField(max_length=12, verbose_name='平石类型')),
                ('平石长度', models.FloatField(verbose_name='平石长度')),
                ('路面类型', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='patrolManagementUI.路面类型', verbose_name='路面类型')),
            ],
        ),
        migrations.CreateModel(
            name='道路等级',
            fields=[
                ('道路等级', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='道路等级')),
            ],
        ),
        migrations.CreateModel(
            name='道路基本档案',
            fields=[
                ('道路编号', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='道路编号')),
                ('道路名称', models.CharField(max_length=100, verbose_name='道路名称')),
                ('道路走向', models.CharField(max_length=100, verbose_name='道路走向')),
                ('起点', models.CharField(max_length=100, verbose_name='起点')),
                ('终点', models.CharField(max_length=100, verbose_name='终点')),
                ('设计单位', models.CharField(max_length=100, verbose_name='设计单位')),
                ('施工单位', models.CharField(max_length=100, verbose_name='施工单位')),
                ('路面等级', models.CharField(max_length=10, verbose_name='路面等级')),
                ('设计时速', models.IntegerField(verbose_name='设计时速')),
                ('路幅宽度范围', models.CharField(max_length=100, verbose_name='路幅宽度范围')),
                ('道路长度', models.FloatField(verbose_name='道路长度')),
                ('道路面积', models.FloatField(verbose_name='道路面积')),
                ('AADT', models.FloatField(verbose_name='AADT')),
                ('交通量等级', models.CharField(max_length=4, verbose_name='交通量等级')),
                ('所属乡镇', models.CharField(max_length=100, verbose_name='所属乡镇')),
                ('管理分类', models.CharField(max_length=50, verbose_name='管理分类')),
                ('管理单位', models.CharField(max_length=50, verbose_name='管理单位')),
                ('养护单位', models.CharField(max_length=50, verbose_name='养护单位')),
                ('建造年月', models.DateField(verbose_name='建造年月')),
                ('车行道编号', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrolManagementUI.车行道')),
                ('道路等级', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='patrolManagementUI.道路等级', verbose_name='道路等级')),
            ],
        ),
        migrations.CreateModel(
            name='定期任务',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('巡查日期', models.DateField(verbose_name='巡查日期')),
                ('道路名称', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadName', to='patrolManagementUI.道路基本档案', verbose_name='巡查道路名称')),
                ('道路等级', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadLevel', to='patrolManagementUI.道路基本档案', verbose_name='巡查道路等级')),
                ('道路编号', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadNumber', to='patrolManagementUI.道路基本档案', verbose_name='巡查道路编号')),
            ],
            options={
                'verbose_name': '定期任务',
                'verbose_name_plural': '定期任务',
            },
        ),
    ]
