# Generated by Django 3.0 on 2019-12-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0003_路面类型_车行道'),
        ('patrolManagementUI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='车行道',
            name='路面类型',
        ),
        migrations.RemoveField(
            model_name='道路基本档案',
            name='车行道编号',
        ),
        migrations.RemoveField(
            model_name='道路基本档案',
            name='道路等级',
        ),
        migrations.RemoveField(
            model_name='定期任务',
            name='道路名称',
        ),
        migrations.RemoveField(
            model_name='定期任务',
            name='道路等级',
        ),
        migrations.RemoveField(
            model_name='定期任务',
            name='道路编号',
        ),
        migrations.AddField(
            model_name='定期任务',
            name='道路基本档案',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='municipalManagementUI.道路基本档案'),
        ),
        migrations.DeleteModel(
            name='路面类型',
        ),
        migrations.DeleteModel(
            name='车行道',
        ),
        migrations.DeleteModel(
            name='道路基本档案',
        ),
        migrations.DeleteModel(
            name='道路等级',
        ),
    ]
