# Generated by Django 3.0 on 2019-12-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0004_auto_20191226_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='定期巡查',
            old_name='道路基本档案',
            new_name='巡查道路',
        ),
        migrations.RenameField(
            model_name='日常巡查',
            old_name='道路编号',
            new_name='巡查道路',
        ),
        migrations.RemoveField(
            model_name='日常巡查',
            name='道路名称',
        ),
    ]
