# Generated by Django 3.0 on 2019-12-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0005_auto_20191226_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='定期巡查',
            name='巡查状态',
            field=models.CharField(choices=[('1', '已巡查'), ('2', '未巡查')], default='未巡查', max_length=20, verbose_name='巡查状态'),
        ),
        migrations.AddField(
            model_name='日常巡查',
            name='巡查状态',
            field=models.CharField(choices=[('1', '已巡查'), ('2', '未巡查')], default='未巡查', max_length=20, verbose_name='巡查状态'),
        ),
    ]
