# Generated by Django 3.0 on 2019-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0005_auto_20191226_1724'),
    ]

    operations = [

    ]
