# Generated by Django 3.0 on 2019-12-30 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0014_道路技术状况评价年报表'),
        ('patrolManagementUI', '0006_auto_20191229_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='定期检测记录',
            fields=[
                ('定期检查记录编号', models.AutoField(primary_key=True, serialize=False, verbose_name='定期检查记录编号')),
                ('巡查日期', models.DateField(auto_now_add=True, verbose_name='巡查日期')),
                ('道路编号', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='municipalManagementUI.道路基本档案', verbose_name='道路编号')),
            ],
        ),
        migrations.CreateModel(
            name='路面平整度检测记录',
            fields=[
                ('平整度检测记录编号', models.AutoField(primary_key=True, serialize=False, verbose_name='平整度检测记录编号')),
                ('IRI', models.FloatField()),
                ('备注', models.CharField(max_length=100)),
                ('定期检查记录编号', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='patrolManagementUI.定期检测记录', verbose_name='定期检查记录编号')),
            ],
        ),
        migrations.CreateModel(
            name='路面定期检查损害记录',
            fields=[
                ('定期巡察损害记录编号', models.AutoField(primary_key=True, serialize=False, verbose_name='定期巡察损害记录编号')),
                ('起止位置', models.CharField(max_length=100, verbose_name='起止位置')),
                ('检查总长', models.FloatField(verbose_name='检查总长')),
                ('检查总宽', models.FloatField(verbose_name='检查总宽')),
                ('损坏长', models.FloatField(verbose_name='损坏长')),
                ('损坏宽', models.FloatField(verbose_name='损坏宽')),
                ('损坏高', models.FloatField(verbose_name='损坏高')),
                ('损坏位置及情况描述', models.CharField(max_length=100, verbose_name='损坏位置及情况描述')),
                ('定期检查记录编号', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='patrolManagementUI.定期检测记录', verbose_name='定期检查记录编号')),
                ('损坏类型', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='定期巡查损害记录引用损坏类型', to='municipalManagementUI.路面损坏类型', verbose_name='损坏类型')),
                ('路面类型', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='定期巡查损害记录引用路面类型', to='municipalManagementUI.路面损坏类型', verbose_name='路面类型')),
            ],
        ),
        migrations.CreateModel(
            name='日常巡查记录',
            fields=[
                ('日常巡查记录编号', models.AutoField(primary_key=True, serialize=False, verbose_name='日常巡查记录编号')),
                ('巡查日期', models.DateField(verbose_name='巡查日期')),
                ('道路编号', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='municipalManagementUI.道路基本档案', verbose_name='道路编号')),
            ],
            options={
                'verbose_name': '日常巡查记录',
                'verbose_name_plural': '日常巡查记录',
            },
        ),
        migrations.CreateModel(
            name='日常巡查损害记录',
            fields=[
                ('日常巡查损害记录编号', models.AutoField(primary_key=True, serialize=False, verbose_name='日常巡查损害记录编号')),
                ('损坏位置及情况描述', models.CharField(max_length=100, verbose_name='损坏位置及情况描述')),
                ('损坏类型', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='日常巡查损坏记录引用损坏类型', to='municipalManagementUI.路面损坏类型', verbose_name='损坏类型')),
                ('日常巡查记录编号', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='patrolManagementUI.日常巡查记录', verbose_name='日常巡查记录编号')),
                ('路面类型', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='日常巡查损坏记录引用路面类型', to='municipalManagementUI.路面损坏类型', verbose_name='路面类型')),
            ],
            options={
                'verbose_name': '日常巡查损害记录',
                'verbose_name_plural': '日常巡查损害记录',
            },
        ),
    ]
