# Generated by Django 3.0 on 2019-12-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0014_道路技术状况评价年报表'),
        ('patrolManagementUI', '0007_定期检测记录_日常巡查损害记录_日常巡查记录_路面定期检查损害记录_路面平整度检测记录'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='定期检测记录',
            options={'verbose_name': '定期检测记录', 'verbose_name_plural': '定期检测记录'},
        ),
        migrations.AlterModelOptions(
            name='路面定期检查损害记录',
            options={'verbose_name': '路面定期检查损害记录', 'verbose_name_plural': '路面定期检查损害记录'},
        ),
        migrations.AlterModelOptions(
            name='路面平整度检测记录',
            options={'verbose_name': '路面平整度检测记录', 'verbose_name_plural': '路面平整度检测记录'},
        ),
        migrations.AddField(
            model_name='定期检测记录',
            name='巡查人员',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='定期巡查引用职工', to='municipalManagementUI.职工', verbose_name='巡查人员'),
        ),
        migrations.AddField(
            model_name='日常巡查记录',
            name='巡查人员',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='日常巡查引用职工', to='municipalManagementUI.职工', verbose_name='巡查人员'),
        ),
        migrations.AlterField(
            model_name='路面平整度检测记录',
            name='IRI',
            field=models.FloatField(verbose_name='平整度指数'),
        ),
    ]
