# Generated by Django 3.0 on 2019-12-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0007_auto_20191228_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='日常巡查',
            name='道路名称',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='道路名称'),
        ),
        migrations.AlterField(
            model_name='日常巡查',
            name='道路编号',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='道路编号'),
        ),
    ]
