# Generated by Django 3.0 on 2019-12-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0008_auto_20191228_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='日常巡查',
            name='道路名称',
        ),
        migrations.RemoveField(
            model_name='日常巡查',
            name='道路编号',
        ),
        migrations.AlterField(
            model_name='日常巡查',
            name='巡查状态',
            field=models.CharField(choices=[('1', '未巡查'), ('2', '已巡查')], default='未巡查', max_length=20, verbose_name='巡查状态'),
        ),
    ]
