# Generated by Django 3.0 on 2019-12-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0014_道路技术状况评价年报表'),
        ('patrolManagementUI', '0009_auto_20191230_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='定期巡查',
            new_name='定期巡查任务',
        ),
        migrations.RenameModel(
            old_name='日常巡查',
            new_name='日常巡查任务',
        ),
        migrations.AlterModelOptions(
            name='定期巡查任务',
            options={'verbose_name': '定期巡查任务', 'verbose_name_plural': '定期巡查任务'},
        ),
        migrations.AlterModelOptions(
            name='日常巡查任务',
            options={'verbose_name': '日常巡查任务', 'verbose_name_plural': '日常巡查任务'},
        ),
        migrations.AlterField(
            model_name='日常巡查损害记录',
            name='备注',
            field=models.TextField(max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='日常巡查损害记录',
            name='损坏位置及情况描述',
            field=models.TextField(max_length=100, verbose_name='损坏位置及情况描述'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='损坏位置及情况描述',
            field=models.TextField(max_length=100, verbose_name='损坏位置及情况描述'),
        ),
        migrations.AlterField(
            model_name='路面平整度检测记录',
            name='备注',
            field=models.TextField(max_length=100, verbose_name='备注'),
        ),
    ]
