# Generated by Django 3.0 on 2020-01-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0010_auto_20191231_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='路面定期检查损害记录',
            name='路面类型',
        ),
    ]
