# Generated by Django 3.0 on 2020-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0011_remove_路面定期检查损害记录_路面类型'),
    ]

    operations = [
        migrations.AlterField(
            model_name='日常巡查任务',
            name='巡查状态',
            field=models.CharField(choices=[('1', '未巡查'), ('2', '已巡查')], default='1', max_length=20, verbose_name='巡查状态'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='损坏宽',
            field=models.FloatField(default=1, verbose_name='损坏宽'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='损坏长',
            field=models.FloatField(default=1, verbose_name='损坏长'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='损坏高',
            field=models.FloatField(default=1, verbose_name='损坏高'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='检查总宽',
            field=models.FloatField(default=0, verbose_name='检查总宽'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='检查总长',
            field=models.FloatField(default=0, verbose_name='检查总长'),
        ),
    ]
