# Generated by Django 3.0 on 2020-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0012_auto_20200104_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='路面定期检查损害记录',
            name='备注',
            field=models.TextField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='路面定期检查损害记录',
            name='损坏位置及情况描述',
            field=models.TextField(max_length=100, null=True, verbose_name='损坏位置及情况描述'),
        ),
    ]
