# Generated by Django 3.0 on 2020-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrolManagementUI', '0013_auto_20200104_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='定期巡查任务',
            name='巡查状态',
            field=models.CharField(choices=[('1', '未巡查'), ('2', '已巡查')], default='1', max_length=20, verbose_name='巡查状态'),
        ),
    ]
