# Generated by Django 3.0 on 2019-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='职工表',
            fields=[
                ('工号', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='工号')),
                ('姓名', models.CharField(max_length=40, verbose_name='姓名')),
                ('性别', models.CharField(max_length=2, verbose_name='性别')),
                ('职能', models.CharField(max_length=20, verbose_name='职能')),
                ('密码', models.CharField(max_length=40, verbose_name='密码')),
            ],
        ),
    ]
