# Generated by Django 3.0 on 2019-12-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191220_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='职工',
            name='ticket',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ticket'),
        ),
    ]
