# Generated by Django 2.2 on 2019-12-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191220_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='职工',
            name='职能',
            field=models.CharField(choices=[('1', '市政道路管理'), ('2', '道路巡查养护')], default='道路巡查养护', max_length=20, verbose_name='职能'),
        ),
    ]
