# Generated by Django 3.0 on 2019-12-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191220_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='职工',
        ),
    ]
