# Generated by Django 3.0 on 2019-12-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='职工',
            fields=[
                ('工号', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='工号')),
                ('姓名', models.CharField(max_length=40, verbose_name='姓名')),
                ('性别', models.CharField(choices=[('1', '男'), ('2', '女')], default='男', max_length=2, verbose_name='性别')),
                ('职能', models.CharField(choices=[('1', '市政道路管理'), ('2', '道路巡查养护')], default='道路巡查养护', max_length=20, verbose_name='职能')),
                ('密码', models.CharField(max_length=40, verbose_name='密码')),
                ('ticket', models.CharField(blank=True, max_length=30, null=True, verbose_name='ticket')),
            ],
            options={
                'verbose_name': '职工',
                'verbose_name_plural': '职工',
            },
        ),
    ]
