# Generated by Django 3.0 on 2019-12-23 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='道路等级',
            fields=[
                ('道路等级', models.CharField(choices=[('1', '一级'), ('2', '二级'), ('3', '三级'), ('４', '四级')], max_length=4, primary_key=True, serialize=False, verbose_name='道路等级')),
            ],
            options={
                'verbose_name': '道路等级',
                'verbose_name_plural': '道路等级',
            },
        ),
        migrations.CreateModel(
            name='道路基本档案',
            fields=[
                ('道路编号', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='道路编号')),
                ('道路名称', models.CharField(max_length=100, verbose_name='道路名称')),
                ('道路走向', models.CharField(max_length=100, verbose_name='道路走向')),
                ('起点', models.CharField(max_length=100, verbose_name='起点')),
                ('终点', models.CharField(max_length=100, verbose_name='终点')),
                ('设计单位', models.CharField(max_length=100, verbose_name='设计单位')),
                ('施工单位', models.CharField(max_length=100, verbose_name='施工单位')),
                ('路面等级', models.CharField(max_length=10, verbose_name='路面等级')),
                ('设计时速', models.IntegerField(verbose_name='设计时速')),
                ('路幅宽度范围', models.CharField(max_length=100, verbose_name='路幅宽度范围')),
                ('道路长度', models.FloatField(verbose_name='道路长度')),
                ('道路面积', models.FloatField(verbose_name='道路面积')),
                ('AADT', models.FloatField(verbose_name='AADT')),
                ('交通量等级', models.CharField(max_length=4, verbose_name='交通量等级')),
                ('所属乡镇', models.CharField(max_length=100, verbose_name='所属乡镇')),
                ('管理分类', models.CharField(max_length=50, verbose_name='管理分类')),
                ('管理单位', models.CharField(max_length=50, verbose_name='管理单位')),
                ('养护单位', models.CharField(max_length=50, verbose_name='养护单位')),
                ('建造年月', models.DateField(verbose_name='建造年月')),
                ('道路等级', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='municipalManagementUI.道路等级', verbose_name='道路等级')),
            ],
        ),
    ]
