# Generated by Django 3.0 on 2019-12-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0005_auto_20191223_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='路面损坏类型',
            options={'verbose_name': '路面损坏类型', 'verbose_name_plural': '路面损坏类型'},
        ),
        migrations.AlterModelOptions(
            name='路面类型',
            options={'verbose_name': '路面类型', 'verbose_name_plural': '路面类型'},
        ),
        migrations.AlterModelOptions(
            name='车行道',
            options={'verbose_name': '道路的车行道档案', 'verbose_name_plural': '道路的车行道档案'},
        ),
        migrations.AlterModelOptions(
            name='道路基本档案',
            options={'verbose_name': '道路基本档案', 'verbose_name_plural': '道路基本档案'},
        ),
    ]
