# Generated by Django 3.0 on 2019-12-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0007_auto_20191223_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='道路基本档案',
            name='经纬度',
            field=models.CharField(max_length=50, null=True, verbose_name='经纬度'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='AADT',
            field=models.FloatField(null=True, verbose_name='AADT'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='交通量等级',
            field=models.CharField(max_length=4, null=True, verbose_name='交通量等级'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='养护单位',
            field=models.CharField(max_length=50, null=True, verbose_name='养护单位'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='建造年月',
            field=models.DateField(null=True, verbose_name='建造年月'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='所属乡镇',
            field=models.CharField(max_length=100, null=True, verbose_name='所属乡镇'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='施工单位',
            field=models.CharField(max_length=100, null=True, verbose_name='施工单位'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='管理分类',
            field=models.CharField(max_length=50, null=True, verbose_name='管理分类'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='管理单位',
            field=models.CharField(max_length=50, null=True, verbose_name='管理单位'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='终点',
            field=models.CharField(max_length=100, null=True, verbose_name='终点'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='设计单位',
            field=models.CharField(max_length=100, null=True, verbose_name='设计单位'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='设计时速',
            field=models.IntegerField(null=True, verbose_name='设计时速'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='起点',
            field=models.CharField(max_length=100, null=True, verbose_name='起点'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='路幅宽度范围',
            field=models.CharField(max_length=100, null=True, verbose_name='路幅宽度范围'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='路面等级',
            field=models.CharField(max_length=10, null=True, verbose_name='路面等级'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='道路走向',
            field=models.CharField(max_length=100, null=True, verbose_name='道路走向'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='道路长度',
            field=models.FloatField(null=True, verbose_name='道路长度'),
        ),
        migrations.AlterField(
            model_name='道路基本档案',
            name='道路面积',
            field=models.FloatField(null=True, verbose_name='道路面积'),
        ),
    ]
