# Generated by Django 3.0 on 2019-12-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0008_auto_20191223_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='道路基本档案',
            name='经纬度',
        ),
        migrations.AddField(
            model_name='道路基本档案',
            name='纬度',
            field=models.FloatField(null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='道路基本档案',
            name='经度',
            field=models.FloatField(null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='道路等级',
            name='道路等级',
            field=models.CharField(choices=[('1', '一级'), ('2', '二级'), ('3', '三级'), ('4', '四级')], max_length=4, primary_key=True, serialize=False, verbose_name='道路等级'),
        ),
    ]
