# Generated by Django 3.0 on 2019-12-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0009_auto_20191224_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='道路等级',
            name='备注',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
    ]
