# Generated by Django 3.0 on 2019-12-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0010_道路等级_备注'),
    ]

    operations = [
        migrations.CreateModel(
            name='路面损坏单项扣分表',
            fields=[
                ('损坏单项扣分编号', models.AutoField(primary_key=True, serialize=False, verbose_name='损坏单项扣分编号')),
                ('扣分分值', models.IntegerField(verbose_name='扣分分值')),
                ('损坏密度', models.FloatField(verbose_name='损坏密度')),
                ('损坏类型', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='municipalManagementUI.路面损坏类型', verbose_name='损坏类型')),
            ],
            options={
                'verbose_name': '路面损坏单项扣分表',
                'verbose_name_plural': '路面损坏单项扣分表',
            },
        ),
    ]
