# Generated by Django 3.0 on 2019-12-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0011_路面损坏单项扣分表'),
    ]

    operations = [
        migrations.AlterField(
            model_name='路面损坏类型',
            name='要引用的路面类型',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn路面类型', to='municipalManagementUI.路面类型', verbose_name='路面类型'),
        ),
    ]
