# Generated by Django 3.0 on 2020-01-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0014_道路技术状况评价年报表'),
    ]

    operations = [
        migrations.AddField(
            model_name='路面损坏类型',
            name='损坏面积计算方法',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='损坏面积计算方法'),
        ),
    ]
