# Generated by Django 3.0 on 2020-01-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalManagementUI', '0015_路面损坏类型_损坏面积计算方法'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='路面损坏类型',
            name='损坏面积计算方法',
        ),
        migrations.AddField(
            model_name='路面损坏类型',
            name='损坏面积计算方法代号',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='损坏面积计算方法代号'),
        ),
    ]
